name: Install nuget

description: 'Installs the latest version of nuget.exe and installs mono to run nuget.exe'

# Requires the following permissions:
# permissions:
#   contents: read
#   packages: read

inputs:
  path:
    description: 'Directory to place nuget in'
    required: false
    default: '/usr/local/bin'
  gh-token:
    description: 'A token with at least the `package: read` permission'

runs:
  using: "composite"
  steps:
    - name: Log in to the GitHub Packages Container registry
      uses: docker/login-action@v3.3.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.gh-token }}

    - name: Pull image
      id: pull
      run: |
        docker pull $"tag"
        echo "tag=$tag" >> $GITHUB_OUTPUT
      env:
        tag: ghcr.io/jeroenbos/nuget:v0
      shell: bash

    - name: Install nuget
      run: |
        set -e
        echo "docker run '${{ steps.pull.outputs.tag }}' nuget \$@" > '${{ inputs.path }}/nuget'
        chmod +x '${{ inputs.path }}/nuget'
      shell: bash
