name: Install nuget

description: 'Installs the latest version of nuget.exe and installs mono to run nuget.exe'

inputs:
  path:
    description: 'Directory to place nuget in'
    required: false
    type: string
    default: '/usr/local/bin'
  gh-pat:
    description: 'A GitHub Personal Access Token with permission to read packages'
    required: true
    type: string


runs:
  using: "composite"
  steps:
    - name: Verify inputs
      run: |
        [[ -z "${{ inputs.gh-pat }}" ]] && echo "Argument 'gh-pat' is mandatory" && exit 1

    - name: Log in to the GitHub Packages Container registry
      uses: docker/login-action@v3.3.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.gh-pat }}

    - name: Pull image
      id: pull
      run: |
        docker pull "$tag"
        echo "tag=$tag" >> $GITHUB_OUTPUT
      env:
        tag: ghcr.io/jeroenbos/nuget:v1
      shell: bash

    - name: Install nuget
      run: |
        set -e
        echo "docker run '${{ steps.pull.outputs.tag }}' nuget \$@" > '${{ inputs.path }}/nuget'
        chmod +x '${{ inputs.path }}/nuget'
      shell: bash
