name: Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-nuget-setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ./
      - run: nuget --version
