name: Deploy

on:
  push:
    branches: [main]
    paths:
      - "mono/**"
  pull_request:
    paths:
      - "mono/**"

jobs:
  deploy-new-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to the GitHub Packages Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      - name: Build and push image
        uses: docker/build-push-action@v6.9.0
        with:
          context: mono
          push: true # 🚧 ${{ github.event.pull_request && false || true }}
          tags: ghcr.io/jeroenbos/nuget:v0
